### ISSUE TITLE
Failed to install rinchi package

### ISSUE THREAD

**Issue by QizhiSu** [rajarshi/rinchi#2]
Dear rinchi developer, 
I failed to install rinchi package. I am using windows 10 64 bit, jdk 11.0.6 (64 bit), and R 3.6.3 (64 bit). 
below are the code and error I got:
> library(rJava)
> install.packages("remotes")
Installing package into ‘C:/Users/qizhi/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/remotes_2.1.1.zip'
Content type 'application/zip' length 358520 bytes (350 KB)
downloaded 350 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\qizhi\AppData\Local\Temp\RtmpymVbdl\downloaded_packages
> remotes::install_github("CDK-R/rinchi")
Downloading GitHub repo CDK-R/rinchi@master
√  checking for file 'C:\Users\qizhi\AppData\Local\Temp\RtmpymVbdl\remotes1b844637fca\CDK-R-rinchi-d51bd48/DESCRIPTION'
-  preparing 'rinchi':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'rinchi_0.5.tar.gz'
   
Installing package into ‘C:/Users/qizhi/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'rinchi' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rinchi'
    finding HTML links ... done
    getinchi                                html  
    parseinchi                              html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'rinchi':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/qizhi/OneDrive/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/qizhi/OneDrive/Documents/R/win-library/3.6/rinchi'
Error: Failed to install 'rinchi' from GitHub:
  (converted from warning) installation of package ‘C:/Users/qizhi/AppData/Local/Temp/RtmpymVbdl/file1b8423635ac1/rinchi_0.5.tar.gz’ had non-zero exit status
> 

I have checked online for possible reasons causing this error. many of them said JAVA_HOME has not been set properly. however, I have set it properly to my jdk-11.0.6 folder and I don't have problem librarying rJava package.

**Comment by QizhiSu** [comment]
@rajarshi @sneumann Hi, Could you guys help?

**Comment by sneumann** [comment]
Hi, looking at the errors I'd like to see confirmation that rJava 
is indeed installed properly. Can you check the following commands 
in a fresh R session:
```
library(rJava)
.jinit()
```
Yours, Steffen

**Comment by QizhiSu** [comment]
I have run the two commands, they work fine. see the attachment, please.
![image](https://user-images.githubusercontent.com/55191839/79644667-a754d700-81aa-11ea-91ec-2de1adbb57c2.png)

**Comment by sneumann** [comment]
As non-Windows user I am out of ideas. Just one more thing, please copy&paste 
the output of `sessionInfo()` after the .jinit call here. If you copy the text, rather than a screenshot, 
the text can be found via google or github search, which will benefit attracting help. 
Yours, Steffen

**Comment by rajarshi** [comment]
Hi @Sukis123 - sorry for the delay in getting back to you. Unfortunately I don't have a Windows machine to test this. I did try using the [Rhub](https://builder.r-hub.io/) service but it failed to build there ([output log](https://builder.r-hub.io/status/original/rinchi_0.5.tar.gz-c3b6dd472938965cf4c20acb9568daba)) due to an `rjava` issue.

The only thing I can guess is that it may be related to `JAVA_HOME`

Maybe @zachcp has some experience with this?

**Comment by rajarshi** [comment]
So it looks the win-builder service was able to build a Windows package, which I've placed in the repository. Take a look and see if that installs for you (so you don't need to build from sources)

**Comment by Sukis123** [comment]
Thanks a lot. it seems that rinchi was trying to load the 32 bit rJava.dll but not the 64 bit one. I have checked that the 64 bit one is available as well. 

I have download the rinchi_0.5.zip file, but how to install?

**Comment by QizhiSu** [comment]
Thanks a lot. it seems that rinchi was trying to load the 32 bit rJava.dll but not the 64 bit one. I have checked that the 64 bit one is available as well.

I have downloaded the rinchi_0.5.zip now. it works fine. 

thank you very much.

**Comment by rajarshi** [comment]
Closing this issue as it seems to be resolved
